version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.9

executors:
  backend-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

jobs:
  build-backend:
    executor: backend-executor
    steps:
      - checkout
      - run:
          name: Compilar el backend
          command: cd CedulaApi && mvn clean package

  dast-scan:
    machine: true
    steps:
      - checkout
      - run:
          name: Instalar herramientas necesarias
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
      - run:
          name: Crear red Docker
          command: docker network create app-network || true
      - run:
          name: Construir imágenes Docker
          command: docker-compose build
      - run:
          name: Iniciar backend en Docker
          command: |
            docker-compose up -d backend
            echo "Esperando 30 segundos para que el backend arranque..."
            sleep 30
      - run:
          name: Verificar logs del backend
          command: docker-compose logs backend
      - run:
          name: Verificar si el backend responde
          command: |
            for i in {1..15}; do
              if docker-compose run --rm backend curl -s -o /dev/null -w "%{http_code}" "http://backend:8080/api/cedulas/validar?cedula=1721544052" | grep -q "200"; then
                echo "✅ Backend está disponible!"
                exit 0
              fi
              echo "⏳ Intento $i/15 - Esperando backend..."
              sleep 5
            done
            echo "❌ ERROR: Backend no está respondiendo dentro de CircleCI"
            exit 1
      - run:
          name: Ejecutar escaneo con ZAP
          command: |
            docker-compose run --rm \
              -v $(pwd):/zap/wrk \
              zap zap-baseline.py \
              -t http://backend:8080/api/cedulas/validar \
              -r /zap/wrk/zap_report.html \
              -J /zap/wrk/zap_report.json \
              -I -D 60
      - store_artifacts:
          path: zap_report.html
      - store_artifacts:
          path: zap_report.json


workflows:
  version: 2
  build-test-deploy:
    jobs:
      # Habilita lo que necesites según tu orden de build/test.
      - pre-build-frontend
      - pre-build-backend
      - build-frontend:
          requires:
            - pre-build-frontend
      - build-backend:
          requires:
            - pre-build-backend
      - test-frontend:
          requires:
            - build-frontend
      - test-backend:
          requires:
            - build-backend
      - dast-scan:
          requires:
            - test-backend